-- Add 'SUPPORT_TICKET' to the enum type used by public."AuditLog".action

DO $$
DECLARE
  enum_typename text;
BEGIN
  -- Find the enum type name used by the action column
  SELECT t.typname
  INTO enum_typename
  FROM pg_attribute a
  JOIN pg_class c ON c.oid = a.attrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  JOIN pg_type t ON t.oid = a.atttypid
  WHERE n.nspname = 'public'
    AND c.relname = 'AuditLog'    -- <- table name generated by Prisma for model AuditLog
    AND a.attname = 'action';

  IF enum_typename IS NULL THEN
    RAISE EXCEPTION 'Could not find enum type for public."AuditLog".action';
  END IF;

  -- Add value if it doesn't exist yet
  IF NOT EXISTS (
    SELECT 1
    FROM pg_enum e
    JOIN pg_type t ON t.oid = e.enumtypid
    WHERE t.typname = enum_typename
      AND e.enumlabel = 'SUPPORT_TICKET'
  ) THEN
    EXECUTE format('ALTER TYPE %I ADD VALUE ''SUPPORT_TICKET''', enum_typename);
  END IF;
END $$;
